### ISSUE TITLE
released yet ?

### ISSUE THREAD

**Issue by colindaven** [Illumina/paragraph#1]
Hi, I would be interesting in trialling this software. Has it been released yet ?
Seems I would need a password to download. Thanks.

git clone https://github.com/Illumina/paragraph-tools.git
Cloning into 'paragraph-tools'...
Username for 'https://github.com': cxxxxxx
Password for 'https://xxxxxxxxxxxxxxxxxxxxxx': 
remote: Repository not found.
fatal: repository 'https://github.com/Illumina/paragraph-tools.git/' not found

**Comment by pkrusche** [comment]
Hi, sorry, it seems that our command line contains the wrong repository URL. We'll fix this!

Until then, you can use 

```
git clone  https://github.com/Illumina/paragraph.git
```

Hope this helps!

**Comment by colindaven** [comment]
Thanks, that worked

**Comment by pkrusche** [comment]
We have released a new version and updated the documentation. Closing the issue.
