### ISSUE TITLE
Reference sequences do not match error messages would be helpful

### ISSUE THREAD

**Issue by RSherman15** [Illumina/paragraph#12]
Not so much an issue as a suggestion, but it would be great to have some sort of error message in the following cases regarding references not matching, all of which I have encountered and don't give the most informative errors:

If the reference for the short read bam and vcf use differing notation (eg "chr1" vs "1"), it'd be great if this could either be handled by Paragraph, or if Paragraph could do an initial check and report an error to the user.

If the reference used in multigrmpy.py with -r doesn't match the reference sequences from the header, it yields a very uninformative error of "subprocess.CalledProcessError: grmpy --response-file [tempFile] returned non-zero exit status 1". Having a check which tells the user that the reference used with -r does not match would be extremely helpful; it took me quite a while to figure out I was accidentally using the wrong reference (which used "1" instead of "chr1" etc).

**Comment by traxexx** [comment]
Yes. I had this issues before, too. We'll include that in the release after v2.1!
