### ISSUE TITLE
Dockerfile entry point does not match documentation

### ISSUE THREAD

**Issue by WEClarke** [Illumina/paragraph#15]
Documentation states:

> The default entry point is the multigrmpy.py script

However the Dockerfile contains

`CMD ["/opt/paragraph/bin/runGraphTyping.py", "-h"]`

**Comment by traxexx** [comment]
We are going to update the docker. It's based on an older version.

**Comment by traxexx** [comment]
@WEClarke fixed in #22 and will be released as v2.2a
