### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ytguojian** [Illumina/paragraph#2]
Hi,
I have downloaded the lastest version, and use the configure file to install. I was a linux user and did not have root authority. It showed Configuring incomplete, errors occurred.
Is that normal?
Cheers

**Comment by pkrusche** [comment]
Hi there,

Could you please provide some more information? Which Linux distribution are you using, and what was the full output from configure?

Also, our readme file contains more information on requirements and different installation procedures.

**Comment by ytguojian** [comment]
Hi,
The linux distribution is CentOS Linux release 7.4.1708 ; 
The error message is "Using existing /usr/bin/cmake
-- using compiler: g++ version 4.8.5
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.2.2")
Using included htslib
-- Configuring done
-- Generating done
-- Build files have been written to: /powerplant/workspace/hrajxg/software/paragraph-paragraph-v1.1/external/htslib-build
[100%] Built target htslib
CMake Error at src/cmake/GetGoogleTest.cmake:4 (FILE):
  Syntax error in cmake code at

    /workspace/hrajxg/software/paragraph-paragraph-v1.1/src/cmake/GetGoogleTest.cmake:4

  when parsing string

    \

  cmake_minimum_required(VERSION 2.8.5)

  project(googletest-build NONE)

  include(ExternalProject)

  ExternalProject_Add(googletest

          # GIT_REPOSITORY    https://github.com/google/googletest.git
          # GIT_TAG           release-1.8.0
          URL               \"${CMAKE_SOURCE_DIR}/external/googletest-release-1.8.0.tar.gz\"
          URL_HASH          MD5=16877098823401d1bf2ed7891d7dce36
          SOURCE_DIR        \"${CMAKE_BINARY_DIR}/external/googletest-src\"
          BINARY_DIR        \"${CMAKE_BINARY_DIR}/external/googletest-build\"
          CONFIGURE_COMMAND \"\"
          BUILD_COMMAND     \"\"
          INSTALL_COMMAND   \"\"
          TEST_COMMAND      \"\"
          )

  syntax error, unexpected cal_SYMBOL, expecting $end (265)
Call Stack (most recent call first):
  CMakeLists.txt:31 (include)


-- Configuring incomplete, errors occurred!
See also "/workspace/hrajxg/software/paragraph-paragraph-v1.1/CMakeFiles/CMakeOutput.log".
Couldn't configure the project:

cmake -H"/workspace/hrajxg/software/paragraph-paragraph-v1.1" -B"/workspace/hrajxg/software/paragraph-paragraph-v1.1" -G"Unix Makefiles"  -DCMAKE_INSTALL_PREFIX:STRING=/workspace/hrajxg/software/paragraph-paragraph-v1.1/ -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_PARALLEL:INTEGER=1 -DCPACK_PACKAGING_INSTALL_PREFIX:STRING=/workspace/hrajxg/software/paragraph-paragraph-v1.1/     -DCPACK_SYSTEM_NAME:STRING=Linux-x86_64     -DCPACK_PACKAGE_CONTACT:STRING='support@illumina.com'

Moving CMakeCache.txt to CMakeCache.txt.removed"
Cheers,

**Comment by pkrusche** [comment]
I think there are two problems:

* Your version of CMake is probably too old for our process. The CMakefiles specify 2.8.5, but that is not correct, I think > 3.0 is probably the minimum. There is a `cmake3` package from various sources, e.g. https://centos.pkgs.org/7/epel-x86_64/cmake3-3.6.3-1.el7.x86_64.rpm.html
* a newer version of gcc/g++ will be required (> 4.9.x, ideally newer). On Centos, this will be available with a newer devtoolset, e.g. version 7: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by ytguojian** [comment]
Thanks a lot. I will have a try.

**Comment by pkrusche** [comment]
Closing issues -- please reopen if needed.
