### ISSUE TITLE
Alternate reference based on paragraph results

### ISSUE THREAD

**Issue by ascendo** [Illumina/paragraph#21]
Dear Paragraph team,
Do you have any plan to develop a tool which can provide the alternative reference from Paragraph results?
Something similar to FastAlternateReferenceMaker from GATK but need to support structure variations.

https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_fasta_FastaAlternateReferenceMaker.php

Thanks.
Won

**Comment by traxexx** [comment]
With the input VCF + reference fasta, the sequence graph is automatically constructed in Paragraph. We have no plan to update the linear reference in the near future.

**Comment by ascendo** [comment]
Thanks.
