### ISSUE TITLE
Genotype does not meet VCF 4.2 spec

### ISSUE THREAD

**Issue by WEClarke** [Illumina/paragraph#28]
In rare cases Paragraph returns a genotype that does not match the VCF spec; returning a single '.' genotype on non-sex chromosomes. For example I have the following genotypes for 2 samples on chr3. My interpretation is that the second sample should be './.' since it is in a diploid region of the genome.

`0/0:40:....:40,0:20,0:20,0:0,124,599    .:0:NO_VALID_GT,UNMATCHED:0,0:0,0:0,0:.,.,.`

**Comment by traxexx** [comment]
Thanks for pointing that out! Long story short, when there isn't any read aligned to the local graph, the internal genotyper doesn't have the information of ploidy. Does it bring trouble to your downstream analysis?

**Comment by WEClarke** [comment]
Not currently affecting analysis, just wanted to make you aware.

**Comment by traxexx** [comment]
OK I'll leave the issue here. See if we can have some time in the future to reconstruct this data structure.
