### ISSUE TITLE
Runtime exceeds expectations

### ISSUE THREAD

**Issue by WEClarke** [Illumina/paragraph#29]
I have been testing Paragraph and have been experiencing longer than expected runtimes. The stated performance is:

> It typically takes up to a few seconds to genotype a single event in one sample (single-threaded). It took us 30 minutes to genotype ~20,000 SVs using 20 CPU cores (with I/O).

This works out to roughly 1000 SVs per Core per 30min (1.8 seconds/sv single core).

My setup:

- Paragraph version 2.2b via Docker
- Google Cloud instance with 8 VCPU @ 2.3GHz, 7.2GB RAM, Local SSD
- Single sample (23GB CRAM)
- GRCh38 reference w alt+decoy
- 1042 Insertions (called only on Chr 1-22,X,Y)

Results:

| Threads | Runtime (Min) | Seconds/SV/core |
|--------- |-----------|-----------|
| 1 | 123 | 7.08 |
| 2 | 64 | 7.37 |
| 4 | 34 | 7.83 |
| 8 | 26 | 11.98 |

Do you have any feedback as to why these runtimes seem significantly slower than your suggested times?

Cheers,
Wayne

**Comment by traxexx** [comment]
The most time-consuming part is the high-depth region, especially, tandem repeats. With option "-M" (maximum depth in a region) set up to a smaller value (e.g. 10 times the average depth), we get the speed of 1.8s/genotype.

I remember the default "-M" is probably set at a high value.

**Comment by traxexx** [comment]
I added some explanation in v2.3 README for this run time issue.

In general, from our experiments in manuscript, high-depth regions consume the majority of running time, and the result from such repetitive regions are error-prone. For now, I'd recommend skipping them by setting "-M".

We're working on better methods to correctly genotype such repeats. Hopefully, it will be public in the next few months.

Let me know if you still have running time issue by setting "-M" option to 20x depth.
