### ISSUE TITLE
Libraries not linking

### ISSUE THREAD

**Issue by RSherman15** [Illumina/paragraph#3]
I'm having trouble with install; on the htslib build step; I'm using Linux CentOS 6.9 and gcc/g++ 5.1.0.

cmake (I'm using version 3.5.0) seems to find my installed lzma library files just fine:

> -- Found ZLIB: /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/libz.so (found version "1.2.11")
> -- Found BZip2: /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/libbz2.so (found version "1.0.6") 
> -- Looking for BZ2_bzCompressInit
> -- Looking for BZ2_bzCompressInit - found
> -- Looking for lzma_auto_decoder in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so
> -- Looking for lzma_auto_decoder in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so - found
> -- Looking for lzma_easy_encoder in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so
> -- Looking for lzma_easy_encoder in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so - found
> -- Looking for lzma_lzma_preset in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so
> -- Looking for lzma_lzma_preset in /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/lib/liblzma.so - found
> -- Found LibLZMA: /home-4/rsherma8@jhu.edu/bin/packages/miniconda2/include (found version "5.2.3") 

However, it is then unable to find lzma.h.

> [ 75%] Performing build step for 'htslib'
> cram/cram_io.c:61:18: fatal error: lzma.h: No such file or directory
> compilation terminated.
> make[3]: *** [cram/cram_io.o] Error 1
> gmake[2]: *** [htslib-prefix/src/htslib-stamp/htslib-build] Error 2
> gmake[1]: *** [CMakeFiles/htslib.dir/all] Error 2
> gmake: *** [all] Error 2
> CMake Error at src/cmake/GetHtslib.cmake:37 (message):
>   Build step for htslib failed: 2
> Call Stack (most recent call first):
>   CMakeLists.txt:33 (include)
> 
> -- Configuring incomplete, errors occurred!

Pointing DCMAKE_INCLUDE_PATH and DCMAKE_SYSTEM_LIBRARAY_PATH to the correct locations seems to have no effect. Manually modifying the include <lzma.h> in cram_io.c to point to the correct location does fix the immediate problem, but then the following step just fails to find the lzma library.

> /usr/bin/ld: cannot find -llzma
> collect2: error: ld returned 1 exit status
> make[3]: *** [libhts.so] Error 1
> gmake[2]: *** [htslib-prefix/src/htslib-stamp/htslib-build] Error 2
> gmake[1]: *** [CMakeFiles/htslib.dir/all] Error 2
> gmake: *** [all] Error 2
> CMake Error at src/cmake/GetHtslib.cmake:37 (message):
>   Build step for htslib failed: 2
> Call Stack (most recent call first):
>   CMakeLists.txt:33 (include)

Any suggestions on how to get cmake to recognize these installed libraries? I can't figure out why it seems to find them in one step, and then not link to them in subsequent compilation steps.

**Comment by pkrusche** [comment]
Hi,

One possible solution is to use a precompiled htslib that doesn’t depend on liblzma (or has it configured correctly) using cmake -DHTSLIB_INSTALL_PATH=<path to htslib>

For compiling htslib, you can point it to the right liblzma using its configure script or disable liblzma.

Which system are you working on (Linux distribution, version)?

**Comment by RSherman15** [comment]
Thanks, setting -DHTSLIB_INSTALL_PATH did the trick. I'm now having other issues compiling, but I'll open a new issue as I believe they are unrelated.
