### ISSUE TITLE
idxdepth underestimating depth of coverage, possibly? 

### ISSUE THREAD

**Issue by dantaki** [Illumina/paragraph#32]
I realigned the 300x Genome in a Bottle AJ Trio samples with bwa since the Illumina paired-end alignments they host were done with novoalign (booo). 

When running idxdepth for the samples I get

* 197.58
* 181.58
* 192.29

in the "depth" entries

However using bedtools genome coverage the values are 

* 297.65
* 323.51
* 292.37

which is closer to the "advertised" coverage from GiaB.

**Comment by traxexx** [comment]
because idxdepth outputs "depth median" as depth, not mean depth. Usually it's lower than mean depth because it is less affected by the ultra high depth regions.

**Comment by jjfarrell** [comment]
In the sample manifest documentation, it refers to the field as the average depth. Sounds like it should be median depth.
