### ISSUE TITLE
Latest docker image not working

### ISSUE THREAD

**Issue by vandhanak** [Illumina/paragraph#33]
Hi,

Would the latest docker image be updated? The docker pull gives the following error:
_Docker pull fails, Error: /usr/bin/python3: can't open file
'/opt/paragraph/bin/runGraphTyping.py': [Errno 2] No such file or directory_

Thanks!

**Comment by traxexx** [comment]
the docker image has been udpated in v2.3. which version are you using?

**Comment by vandhanak** [comment]
@traxexx: Thanks, will build the image using v2.3. Previously, I had tried pulling an old docker image directly from DockerHub (pkrusche/paragraph) which had no specific tag.

**Comment by traxexx** [comment]
ok that's a much older version. Let me know if you have problems with v2.3 docker.
