### ISSUE TITLE
Distance between vcf position and chrom start is smaller than read length.

### ISSUE THREAD

**Issue by MaoYafei** [Illumina/paragraph#38]
Hi All,

I try to run paragraph to my test dataset. but got an error below:

> $ python3 ../../../Tools/paragraph/bin/multigrmpy.py -i ../pbsv_sample_Bonobo_sv.vcf.gz -m sample.txt -r ../ref.fa -o test &
> [1] 39497
> $ 2020-02-04 16:37:34,250 ERROR    VCF to JSON conversion failed.
> 2020-02-04 16:37:34,303 ERROR    Traceback (most recent call last):
> 2020-02-04 16:37:34,303 ERROR      File "../../../Tools/paragraph/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
> 2020-02-04 16:37:34,303 ERROR      File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json    header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
> 2020-02-04 16:37:34,304 ERROR      File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines    raise Exception("Distance between vcf position and chrom start is smaller than read length.")
> 2020-02-04 16:37:34,304 ERROR    Exception: Distance between vcf position and chrom start is smaller than read length.
> 2020-02-04 16:37:34,305 ERROR    Traceback (most recent call last):
> 2020-02-04 16:37:34,305 ERROR      File "../../../Tools/paragraph/bin/multigrmpy.py", line 261, in run    graph_files = load_graph_description(args)
> 2020-02-04 16:37:34,305 ERROR      File "../../../Tools/paragraph/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
> 2020-02-04 16:37:34,305 ERROR      File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json    header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
> 2020-02-04 16:37:34,306 ERROR      File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines    raise Exception("Distance between vcf position and chrom start is smaller than read length.")
> 2020-02-04 16:37:34,306 ERROR    Exception: Distance between vcf position and chrom start is smaller than read length.
> Traceback (most recent call last):
>   File "../../../Tools/paragraph/bin/multigrmpy.py", line 353, in <module>
>     main()
>   File "../../../Tools/paragraph/bin/multigrmpy.py", line 349, in main
>     run(args)
>   File "../../../Tools/paragraph/bin/multigrmpy.py", line 261, in run
>     graph_files = load_graph_description(args)
>   File "../../../Tools/paragraph/bin/multigrmpy.py", line 52, in load_graph_description
>     header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
>   File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json
>     header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
>   File "/net/eichler/vol26/projects/primate_sv/nobackups/Tools/paragraph/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines
>     raise Exception("Distance between vcf position and chrom start is smaller than read length.")
> Exception: Distance between vcf position and chrom start is smaller than read length.

Here is my manifest file:

> $ cat sample.txt 
> id	path	idxdepth
> bonobo_10	aln_realigned_reads.bam	aln_realigned_reads.bam.json
> $ ls aln_realigned_reads.bam
> aln_realigned_reads.bam
> $ ls aln_realigned_reads.bam.json
> aln_realigned_reads.bam.json

Do you have any idea about it?

Thank you so much.

Best,
Yafei

**Comment by traxexx** [comment]
Hi @MaoYafei Could you please check if your VCF contains a record with POS value smaller than your read length? That should be the reason. The graph alignment needs the flanking to be at least one read-length long. If the variant is too close to the start of the chromosome, there is no way to build a good graph for it.
I will update the error message to make it more precise.

**Comment by netwon123** [comment]
coule u solve this problem?

**Comment by pingxinxing** [comment]
Hello, have you solved this problem successfully? What is the solution?

**Comment by ghost** [comment]
> 您好，您能否检查您的 VCF 是否包含 POS 值小于读取长度的记录？那应该是原因。图形对齐需要侧翼至少有一个读取长度。如果变体太接近染色体的起点，就没有办法为它构建一个好的图形。我将更新错误消息以使其更精确。

Hello sir, I am also experiencing the same problem, could you please provide a more detailed method or give an example

**Comment by ghost** [comment]
Hello, have you solved this problem successfully? What is the solution? # #/ @MaoYafei @traxexx
