### ISSUE TITLE
How to prepare vcf file for Duplication & Tandem Duplication?

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [Illumina/paragraph#41]
Hi, 
I'm trying paragraph for genotyping DUP & TDUP with the following command:
python3 ~/miniconda3/pkgs/paragraph-2.3-h8908b6f_0/bin/multigrmpy.py -i TDUP.vcf -m samples.txt -r ~/reference/genome.fa -o TDUP

Here are some of the contents in samples.txt & TDUP.vcf file:
![image](https://user-images.githubusercontent.com/24313587/76140921-4231a000-609a-11ea-9134-681ae849858e.png)

![image](https://user-images.githubusercontent.com/24313587/76140888-e49d5380-6099-11ea-8eb6-e534a8bf6292.png)

But 75% of genotypes are missing when genotyping DUP & TDUP.
![image](https://user-images.githubusercontent.com/24313587/76141110-2b8c4880-609c-11ea-916d-36a84ae23be6.png)

Could you give me some advice? Thanks!

Zhiliang

**Comment by traxexx** [comment]
Hi Zhiliang,

In real practice Paragraph treats duplications as insertions. With such treatment, the similarity between duplications can significant lower the genotyping performance. And for large DUPs (the one at 1:2388494), the best genotyping method should be read depth counting, but it's not in Paragraph current version yet. Let me check if there is any other good solutions for this case.

**Comment by traxexx** [comment]
For now maybe try GenomeStrip for CNVs? It should work for both discovery and genotyping mode:
http://software.broadinstitute.org/software/genomestrip/
It will work better if you have a bunch of samples running together.

**Comment by Zhiliang-Zhang** [comment]
> For now maybe try GenomeStrip for CNVs? It should work for both discovery and genotyping mode:
> http://software.broadinstitute.org/software/genomestrip/
> It will work better if you have a bunch of samples running together.

Hi,
Thanks for your reply and advice. That sounds great and I will have a try.

Zhiliang
