### ISSUE TITLE
error reference_sequence.empty

### ISSUE THREAD

**Issue by KamilSJaron** [Illumina/paragraph#46]
Hello again,

My testing on few individuals has passed (#42 ), but when I run it on all the data I got, I run into one more issue:

```
[2020-05-08 15:03:10.357] [Genotyping] [16979] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1037) ; 213 were filtered]
[2020-05-08 15:03:10.358] [Genotyping] [16979] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:10.360] [Genotyping] [16973] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1051) ; 199 were filtered]
[2020-05-08 15:03:10.360] [Genotyping] [16973] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:10.362] [Genotyping] [16986] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1052) ; 198 were filtered]
[2020-05-08 15:03:10.363] [Genotyping] [16986] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:10.373] [Genotyping] [16977] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1047) ; 203 were filtered]
[2020-05-08 15:03:10.373] [Genotyping] [16977] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:10.379] [Genotyping] [16985] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1051) ; 199 were filtered]
[2020-05-08 15:03:10.379] [Genotyping] [16985] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:10.481] [Genotyping] [16976] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:10.693] [Genotyping] [16975] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:10.863] [Genotyping] [16974] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:11.080] [Genotyping] [16987] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:11.097] [Genotyping] [16982] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1042) ; 208 were filtered]
[2020-05-08 15:03:11.100] [Genotyping] [16982] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:11.100] [Genotyping] [16980] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:11.302] [Genotyping] [16972] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:11.524] [Genotyping] [16984] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:11.752] [Genotyping] [16981] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:11.961] [Genotyping] [16978] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:12.149] [Genotyping] [16979] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:12.322] [Genotyping] [16973] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:12.543] [Genotyping] [16986] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:12.791] [Genotyping] [16977] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:13.006] [Genotyping] [16985] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:13.246] [Genotyping] [16982] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:13.514] [Genotyping] [16980] [critical] ERROR: This thread also caught an exception
[2020-05-08 15:03:13.514] [Genotyping] [16972] [warning] WARNING: rethrowing a thread exception 
[2020-05-08 15:03:13.906] [Genotyping] [16972] [critical] Assertion failed: !reference_sequence.empty()
```

It complains about an empty reference, but I am not sure which SV is causing the trouble.

When I grepped `16972` out of the log file, the last-mentioned variant
[tmpumt4us9n.json.zip](https://github.com/Illumina/paragraph/files/4599911/tmpumt4us9n.json.zip) and indeed, the json contains some NNNNNs.

The sequence of the corresponding is:

```
>4_Tte_b3v08_scaf031309
TAGCGTAATTAGTACTTAAGCGTATAACCCGAACGGGTAGTAAGACGCGGTGCTAAATAA
TAATAATAATAATAATAATCTAAACAATATACAAATTAAGAAGCGTACTATTCAATTCTT
AGTGGCATGGATTTACAAATGATTTGTTGGGTACAAGACAAACTATAATTCAAAGTTGAA
CTAATTTCTAATTGATGTAATTATGTAATATAAGTTATTACAAAAAAAAAAAGTGTGGCG
TCATTAAAATTAAGTTAGATCGTGTGATAAAATAAGCGTGTGTGTGTGTGTGCAAGACGA
CGCAATAAATCACGGTGTTAAAAATGACCGTTACGTCACTGTTTGTCGGCCAATGAATGA
ATCGCCATAGTCATATTTCTGCTAACGTCCGTGAGATCGGATGAAATATAACCTGAGAAC
CGTAGCCTGTTATTTTAGAACTGGAGACAAATAGATGTTAGTTCAACTCTGATGTAACTT
CTAGTACAGAAACAGGTGGTCAGAACATTCACTAGAATCAGGAGGTCCCTGCCGCTAATA
GCCCCCCTCCCGCGAAAACAAACCTTAACATAATAATACAAAGCGGTGTCTCCCAAACTG
GGGTACGCGTGACCCTGGAGGTATGCTACGCCACATGTGTGTGTTTTTTTTAGCACCGCG
TCTTACTACCAGTTCGGGGTATACGCTTGTATACTAATCATTACAGTAGTGGTTTTAAGG
ATTAGGAAGATTATATTTAGAGGAAGTGTACCCGCATTAACGTGGAGAGAGAGTGAAAAA
CCATTTTGGAAAAATAACCTTGGTACATCCAACAAATATTCGAACTTCGATCGCCGCGTC
ATCGGAAATCTAGTCTATTGCGAGAGTAGAGTAGCGACTTAGACCATGCGGCCAATCGTT
GTATTAAACATCTTTTGAATAACTTGTTGGTATTATGTAACTTTAATTCGATTTTGTTTG
GGTCTGTCAAATTCCACCGCGCGTGATTAAAGTGTCGATAGATTAAATCTAGAAGAATTG
ATGTTTTGTGTAATTTCGCTTTCAATCTTAAGCTTTTTTAAAAAAAAAAAAGATGTTGTA
ATGAAGTAGGACTAAGTATTAGGCCATAATACTGTCCAAACAATAATTTTAAACTAGTCA
TCGGACCTTGGGGGGAGAATCACAAGAGTCAACANTAGGAGTTTTATGCATTTCTACAAA
TCAATGCCTTACTTTAGAGATCATTCCCGATGTTTTATGACATTGGGAACTCTCATAATA
ACATCCATATATATTCGGTGATTAACGTAAACTTTATATGTATGTATACATTTTATATAA
CTAGGCATATATATGTATAATTTTACTATATAAAAATAAAAGGAATTGTTTGTCTGTGTT
TGTTTGTGTGCGATGCCCAGCCAAATTTACGGCACGCAGAGATCTAAAAAAATTTAACAT
AGGTGGACGGAAGGGGGTCCGAATGCACCTCGAAGCAGGATTTTTAAATTTTTAATTAGC
TTTTTAATTAGG
```

and the nucleotide range of the variant (1176-1325) should be (probably):

```
TAGGAGTTTTATGCATTTCTACAAATCAATGCCTTACTTTAGAGATCATTCCCGATGTTTTATGACATTGGGAACTCTCATAATAACATCCATATATATTCGGTGATTAACGTAAACTTTATATGTATGTATACATTTTATATAACTAGG
```

certainly does not seem full of Ns. Originally this sequence was masked (I tried paragraph both with masked and unmasked reference, but I did not try to remap reads on the unmasked ref).

Sorry to bother you again, but I think there is just something rather small I am missing now.

**Comment by traxexx** [comment]
hmmm can i see how your vcf record looks like?

**Comment by KamilSJaron** [comment]
This is the variant

```
4_Tte_b3v08_scaf031309	1174	MantaINS:56259:0:0:0:0:0	AN	ATTTGTGCTTGTCCAAATCACAGGGTGTGTAGTAAAGACAGCGTCAAGTCACGCGTTA	443	PASS	END=1175;SVTYPE=INS;SVLEN=57;CIGAR=1M57I1D	GT:FT:GQ:PL:PR:SR	1/1:PASS:27:496,30,0:0,0:0,13
```

Now I see that the reference is AN, which is somehow confusing when I think about it now. Is that where the problem is?

**Comment by traxexx** [comment]
i don't have a bam here so i can only repeat the vcf conversion step. I got a warning message saying the REF column is different from the reference fasta, which is as expected. Which paragraph version are you using?

**Comment by KamilSJaron** [comment]
I am usung the latest commit: ea342ac00861b42fe9a7f09733a52e95f29f50f2

Would it be useful to extract you bam record of that one scaffold?

**Comment by traxexx** [comment]
that will be useful. A bamlet is enough. Thanks!

**Comment by KamilSJaron** [comment]
I am not sure what is bamlet, but I extracted reads mapping to the scaffold `4_Tte_b3v08_scaf031309`. (sorry the header is a bit bulky)

[Tte_01_4_Tte_b3v08_scaf031309.bam.zip](https://github.com/Illumina/paragraph/files/4745978/Tte_01_4_Tte_b3v08_scaf031309.bam.zip)

**Comment by mebius-S** [comment]
Hello, I would like to ask, from which log file did you grep 16972? There is only the log file grmpy.log in the folder I generated.

> 大家好，
> 
> 我对少数人的测试通过了（#42），但是当我对获得的所有数据运行它时，我遇到了另一个问题：
> 
> ```
> [2020-05-08 15:03:10.357] [Genotyping] [16979] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1037) ; 213 were filtered]
> [2020-05-08 15:03:10.358] [Genotyping] [16979] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:10.360] [Genotyping] [16973] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1051) ; 199 were filtered]
> [2020-05-08 15:03:10.360] [Genotyping] [16973] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:10.362] [Genotyping] [16986] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1052) ; 198 were filtered]
> [2020-05-08 15:03:10.363] [Genotyping] [16986] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:10.373] [Genotyping] [16977] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1047) ; 203 were filtered]
> [2020-05-08 15:03:10.373] [Genotyping] [16977] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:10.379] [Genotyping] [16985] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1051) ; 199 were filtered]
> [2020-05-08 15:03:10.379] [Genotyping] [16985] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:10.481] [Genotyping] [16976] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:10.693] [Genotyping] [16975] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:10.863] [Genotyping] [16974] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:11.080] [Genotyping] [16987] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:11.097] [Genotyping] [16982] [info] [Done with alignment step 1250 total aligned (path: 0 [0 anchored] kmers: 0 / ksw: 0 / gssw: 1042) ; 208 were filtered]
> [2020-05-08 15:03:11.100] [Genotyping] [16982] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:11.100] [Genotyping] [16980] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:11.302] [Genotyping] [16972] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:11.524] [Genotyping] [16984] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:11.752] [Genotyping] [16981] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:11.961] [Genotyping] [16978] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:12.149] [Genotyping] [16979] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:12.322] [Genotyping] [16973] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:12.543] [Genotyping] [16986] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:12.791] [Genotyping] [16977] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:13.006] [Genotyping] [16985] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:13.246] [Genotyping] [16982] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:13.514] [Genotyping] [16980] [critical] ERROR: This thread also caught an exception
> [2020-05-08 15:03:13.514] [Genotyping] [16972] [warning] WARNING: rethrowing a thread exception 
> [2020-05-08 15:03:13.906] [Genotyping] [16972] [critical] Assertion failed: !reference_sequence.empty()
> ```
> 
> 它抱怨一个空引用，但我不确定哪个 SV 导致了这个问题。
> 
> 当我`16972`从日志文件中 grep 出最后提到的变体 [tmpumt4us9n.json.zip](https://github.com/Illumina/paragraph/files/4599911/tmpumt4us9n.json.zip)时，事实上，json 包含一些 NNNNN。
> 
> 对应的顺序为：
> 
> ```
> >4_Tte_b3v08_scaf031309
> TAGCGTAATTAGTACTTAAGCGTATAACCCGAACGGGTAGTAAGACGCGGTGCTAAATAA
> TAATAATAATAATAATAATCTAAACAATATACAAATTAAGAAGCGTACTATTCAATTCTT
> AGTGGCATGGATTTACAAATGATTTGTTGGGTACAAGACAAACTATAATTCAAAGTTGAA
> CTAATTTCTAATTGATGTAATTATGTAATATAAGTTATTACAAAAAAAAAAAGTGTGGCG
> TCATTAAAATTAAGTTAGATCGTGTGATAAAATAAGCGTGTGTGTGTGTGTGCAAGACGA
> CGCAATAAATCACGGTGTTAAAAATGACCGTTACGTCACTGTTTGTCGGCCAATGAATGA
> ATCGCCATAGTCATATTTCTGCTAACGTCCGTGAGATCGGATGAAATATAACCTGAGAAC
> CGTAGCCTGTTATTTTAGAACTGGAGACAAATAGATGTTAGTTCAACTCTGATGTAACTT
> CTAGTACAGAAACAGGTGGTCAGAACATTCACTAGAATCAGGAGGTCCCTGCCGCTAATA
> GCCCCCCTCCCGCGAAAACAAACCTTAACATAATAATACAAAGCGGTGTCTCCCAAACTG
> GGGTACGCGTGACCCTGGAGGTATGCTACGCCACATGTGTGTGTTTTTTTTAGCACCGCG
> TCTTACTACCAGTTCGGGGTATACGCTTGTATACTAATCATTACAGTAGTGGTTTTAAGG
> ATTAGGAAGATTATATTTAGAGGAAGTGTACCCGCATTAACGTGGAGAGAGAGTGAAAAA
> CCATTTTGGAAAAATAACCTTGGTACATCCAACAAATATTCGAACTTCGATCGCCGCGTC
> ATCGGAAATCTAGTCTATTGCGAGAGTAGAGTAGCGACTTAGACCATGCGGCCAATCGTT
> GTATTAAACATCTTTTGAATAACTTGTTGGTATTATGTAACTTTAATTCGATTTTGTTTG
> GGTCTGTCAAATTCCACCGCGCGTGATTAAAGTGTCGATAGATTAAATCTAGAAGAATTG
> ATGTTTTGTGTAATTTCGCTTTCAATCTTAAGCTTTTTTAAAAAAAAAAAAGATGTTGTA
> ATGAAGTAGGACTAAGTATTAGGCCATAATACTGTCCAAACAATAATTTTAAACTAGTCA
> TCGGACCTTGGGGGGAGAATCACAAGAGTCAACANTAGGAGTTTTATGCATTTCTACAAA
> TCAATGCCTTACTTTAGAGATCATTCCCGATGTTTTATGACATTGGGAACTCTCATAATA
> ACATCCATATATATTCGGTGATTAACGTAAACTTTATATGTATGTATACATTTTATATAA
> CTAGGCATATATATGTATAATTTTACTATATAAAAATAAAAGGAATTGTTTGTCTGTGTT
> TGTTTGTGTGCGATGCCCAGCCAAATTTACGGCACGCAGAGATCTAAAAAAATTTAACAT
> AGGTGGACGGAAGGGGGTCCGAATGCACCTCGAAGCAGGATTTTTAAATTTTTAATTAGC
> TTTTTAATTAGG
> ```
> 
> 并且变体 (1176-1325) 的核苷酸范围应该（可能）是：
> 
> ```
> TAGGAGTTTTATGCATTTCTACAAATCAATGCCTTACTTTAGAGATCATTCCCGATGTTTTATGACATTGGGAACTCTCATAATAACATCCATATATATTCGGTGATTAACGTAAACTTTATATGTATGTATACATTTTATATAACTAGG
> ```
> 
> 当然看起来不是全是 N。最初这个序列是被屏蔽的（我尝试了带有屏蔽和未屏蔽引用的段落，但我没有尝试在未屏蔽引用上重新映射读取）。
> 
> 很抱歉再次打扰您，但我认为我现在只是忽略了一些小事。

**Comment by KamilSJaron** [comment]
Sorry, I am not sure if I would be able to find these files anymore.

Thanks for your help.

**Comment by mebius-S** [comment]
> Sorry, I am not sure if I would be able to find these files anymore.
> 
> Thanks for your help.

Thank you for your answer. I would like to ask how you find the wrong variant after this error occurs.
`[2020-05-08 15:03:13.906] [Genotyping] [16972] [critical] Assertion failed: !reference_sequence.empty()`

**Comment by bbimber** [comment]
@mebius-S: I am running into this same "assert !reference_sequence.empty()" error. I dont know yet whether it's dataset-specific or variant-specific (i.e. one particular SV is problematic).

I am trying to find a good way to diagnose which specific variant (our input is 350K SVs) is triggering this. Is there any strategy other than subsetting my VCF and trying one after another to see what dies?

**Comment by mebius-S** [comment]
> @mebius-S: I am running into this same "assert !reference_sequence.empty()" error. I dont know yet whether it's dataset-specific or variant-specific (i.e. one particular SV is problematic).
> 
> I am trying to find a good way to diagnose which specific variant (our input is 350K SVs) is triggering this. Is there any strategy other than subsetting my VCF and trying one after another to see what dies?

Hello, I didn't find this variant in the end, but I deleted the unidentified chromosomes except the autosomes and sex chromosomes in the input vcf file, and then this error no longer appeared.

**Comment by bbimber** [comment]
@mebius-S, it seems like we are running into similar problems. I had an insight into finding the problematic variant. multigrmpy ends up writing a text file with command to pass to grmpy. The stacktrace of your exception probably lists that file. If you inspect that file, it's something like;
```
-r <GENOME_FASTA> -m /work/coverage.txt -o /work/HF97/genotypes.json.gz -z -t 12 --log-level=debug --log-file /work/HF97/grmpy.log --log-async no -g 
/path/to/json1
/path/to/json2
/path/to/json3
/path/to/json4
etc.
```

Where I believe each of these JSON files is one variant. I wrote a script to iterate over each JSON file and execute grmpy for just that one file, rather than in a batch. This will identify which specific file/variant is the problem.
