### ISSUE TITLE
Using more than one input VCF file

### ISSUE THREAD

**Issue by martinghunt** [Illumina/paragraph#47]
I have paragraph working using `multigrmpy.py` on test data using one VCF as input. My use case is actually having two different VCF files for the same sample, made using independent methods. Is it possible for paragraph to use both VCFs, ie build a graph from the union of all the variants from both VCF files, and then genotype? I've been trying out the `vcf2paragraph.py` and `addVariants.py` scripts, but not managed to do it.

**Comment by traxexx** [comment]
the scripts wasn't designed to do so. for now Paragraph doesn't take more than 1 vcf, but you can try to label your vcf in FILTER or INFO field and then merge them together. Paragraph won't remove your original FILTER or INFO flag. Then you can split them after genotyping.
