### ISSUE TITLE
Errors when make

### ISSUE THREAD

**Issue by heyaoxi** [Illumina/paragraph#48]
Hello, I got the error information as below when I 'make' the Paragraph as Installation.md said: 

[ 64%] Building CXX object external/graphtools-
/gpfs/home/heyaoxi/boost_1_65_0/paragraph-tools-build/external/graphtools-src/src/graphIO/../../external/include/nlohmann/json.hpp:8678:43: error: logical ‘and’ of mutually exclusive tests is always false [-Werror=logical-op]
         const bool is_negative = (x <= 0) and (x != 0);  // see issue #755 
cc1plus: all warnings being treated as errors
make[2]: *** [external/graphtools-build/src/graphIO/CMakeFiles/graphIO.dir/build.make:83: external/graphtools-build/src/graphIO/CMakeFiles/graphIO.dir/GraphJson.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:571: external/graphtools-build/src/graphIO/CMakeFiles/graphIO.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

I saw the issue #755 and changed some code as recommended: changed "const bool is_negative = x < 0;" to "const bool is_negative = std::is_same<NumberType, number_integer_t>::value and (x < 0);" but I got new error information:
collect2: error: ld returned 1 exit status
make[2]: *** [src/c++/main/CMakeFiles/grmpy.dir/build.make:115: bin/grmpy] Error 1
make[1]: *** [CMakeFiles/Makefile2:653: src/c++/main/CMakeFiles/grmpy.dir/all] Error 2
make: *** [Makefile:150: all] Error 2.

Is anyone could give some help here?

--Yaoxi

**Comment by traxexx** [comment]
sounds like an environment we issue we had before. how about trying the static version in the release? in that way you don't need to make from scratch
