### ISSUE TITLE
idxdepth error

### ISSUE THREAD

**Issue by biozzq** [Illumina/paragraph#49]
Hi @traxexx 

Thank you for this nice tool. I tried to run following command to generate the general statistics of the BAM file, but the program exited. Also, the warning is strange as the BAM file was generated by mapping to the reference.fa which was passed as an argument to option `-r`. Moreover, can we add an option to filter out the reads with low mapping quality? Thank you.
`idxdepth -b $input.sort.dedup.bam --bam-index $input.sort.dedup.bai -r reference.fa --autosome-regex '[1-9][0-9]?' --sex-chromosome-regex '[XY]?' --threads 1 -o $input --log-level info`
[2020-07-13 19:44:55.015] [idxdepth] [7450] [info] BAM: $input.sort.dedup.bam
[2020-07-13 19:44:55.023] [idxdepth] [7450] [info] Reference: reference.fa
[2020-07-13 19:44:55.023] [idxdepth] [7450] [info] Output path: $input
[2020-07-13 19:44:55.202] [idxdepth] [7450] [warning] BAM header only has a subset of the reference chromosomes -- please make sure they match!
[2020-07-13 19:44:55.209] [idxdepth] [7450] [critical] Assertion failed: index

Sincerely,
Zheng Zhuqing

**Comment by traxexx** [comment]
Looks like your bam header only contains a subset of chromosomes in your reference file. This is not common. Even though there is no reads aligned to one chromosome/contig, the chromosome/contig should still exist in the bam header. Is there a reason for them not being there?

**Comment by biozzq** [comment]
Dear @traxexx 

Thanks. I found that the idxdepth can run smoothly now, however, it always gives me following warning.
`[warning] BAM header only has a subset of the reference chromosomes -- please make sure they match!`

Best,
Zheng Zhuqing

**Comment by traxexx** [comment]
your bam header SQ only contains a subset of reference chromosomes, compared to your reference fasta. I'd suggest checking how the bam was generated. It doesn't seem to be right...

**Comment by Deeeeen** [comment]
> 

Hi, I'm wondering how you resolve this `[critical] Assertion failed: index` problem. Currently I am encountering the same issue. Thanks.

Den
