### ISSUE TITLE
Test output not in expected format

### ISSUE THREAD

**Issue by RSherman15** [Illumina/paragraph#5]
In the documentation, it is indicated that the format of the output of `paragraph-to-csv.py genotypes.json.gz --genotype-only` should be an ID consisting of the chromosome and position, as below:

> #FORMAT=GT
> #ID SWAPS
> chrA:1500-1509  REF/REF
> chrB:1500-1509  S1/S1
> chrC:1500-1699  REF/S1

Instead, the output looks like this:

> #FORMAT=GT
> #ID	SWAPS
> swaps.vcf@5a0b775f60ed1cd0b938ae09b753ad0207c5ba9f83679f894f17d3d1fd352b6f:2	swap2:1/swap2:1
> swaps.vcf@5a0b775f60ed1cd0b938ae09b753ad0207c5ba9f83679f894f17d3d1fd352b6f:3	REF/swap3:1
> swaps.vcf@5a0b775f60ed1cd0b938ae09b753ad0207c5ba9f83679f894f17d3d1fd352b6f:1	REF/REF

which, while traceable to the chromosome/position via the vcf, is, I think, not the expected format?

**Comment by pkrusche** [comment]
I think this script may be a leftover from the time before there was VCF support, and hasn’t been updated when we changed the variant IDs to allow tracing back to the VCF. At this point, it would probably be more flexible to use bcftools query to produce a CSV/TSV file from the VCF; this script mostly serves as a demonstration how to parse the JSON file which has additional information that is not present in the VCF.

**Comment by RSherman15** [comment]
Great, thanks. I just wanted to be sure everything was working alright, since my output didn't match the example on the test data.
