### ISSUE TITLE
SV calling and genotyping across a population

### ISSUE THREAD

**Issue by biozzq** [Illumina/paragraph#50]
Hi @traxexx 

I wonder how do you generate the candidate SVs that used as input for paragraph when you have many short-read samples and several representative long-read samples. In my mind, I will call SVs using both long-read and short-read samples and then merge them together. During merging, I think the breakpoints will become coarse. Does this affect the genotype results when I do not have a precise breakpoint?

Sincerely,
Zheng Zhuqing

**Comment by traxexx** [comment]
As mentioned in #52 merging calls across different samples could be a problem. That's also the effort that people made in SURVIVOR.
To answer your question: does this affect genotyping result? The answer is yes. Paragraph is a breakpoint genotype. Inaccurate breakpoints will result in a worse genotyping performance. We roughly quantified this effect in our paper, too.

**Comment by biozzq** [comment]
Thanks, I noticed the figure 3 in your paper.
