### ISSUE TITLE
Genotyping unresolved insertions using reads around the breakpoint

### ISSUE THREAD

**Issue by malmarri** [Illumina/paragraph#53]
Hi,

Some SV callers can identify unresolved insertions and add the partially assembled insertions around the breakpoint using the LEFT_SVINSSEQ and RIGHT_SVINSSEQ tags in the VCF. paragraph doesn't seem to able to genotype such insertions, but since the algorithm uses reads around the breakpoint it seems like it should be able to do so. Could I request such a feature in the next release?

Thanks,
Mo

**Comment by traxexx** [comment]
Thanks for asking that.

We had that before in the internal version but in the public release, we decided to disable this feature. It can be re-enabled, but in general it is not recommended to do so. Many of these partially assembled insertions are either complex SVs or insertions with inaccurate breakpoints/sequences. For complex SVs a better model is recommended. For inaccurate insertions, Paragraph doesn't work very well (we have a figure in our paper quantifying this effect).

We'll have an option for this. Hopefully before Christmas.
