### ISSUE TITLE
Which aligner?

### ISSUE THREAD

**Issue by fergsc** [Illumina/paragraph#56]
Hi,
I am just starting to investage using Paragraph to genotype some SV within a number of poulations. I shall be doing a lot of alignments of short reads to my references. Is there a preferred aligner to use to generate the bam file for input into paragraph?

thanks.

**Comment by traxexx** [comment]
No preference for aligners. As long as the input BAM is valid and matches your input reference fasta.

**Comment by fergsc** [comment]
Thanks
