### ISSUE TITLE
Temp file directory not settable

### ISSUE THREAD

**Issue by RSherman15** [Illumina/paragraph#6]
An option to set the temp directory manually when running `multigrmpy.py` would be useful. Currently it defaults to putting files in `/tmp` and the server I'm using does not have enough space in that location so I keep getting out of disk space errors. 

I tried setting `--scratch-dir` but if that is what it is intended for, it did not solve the issue - the temporary files still get placed in /tmp, though files get placed in the specified scratch directory as well.

Furthermore, when `multigrmpy.py` errors out, the `/tmp` and `--scratch-dir` directories need to be cleared of their temp files manually.

**Comment by pkrusche** [comment]
I have looked into this and you’re right, there isn’t any cleanup atm — I think this should be easy fix though. 

W.r.t. the location of the files, I do think that at least some of the files should be written to the location specified by `--scratch-dir`; could you perhaps provide a listing / some names of the files that still end up in `/tmp` for you? Also, setting the `TMP` / `TEMP` environment variables could be a workaround to direct these elsewhere:

```bash
export TMP=/my-temp-dir
# ... run paragraph
```

**Comment by RSherman15** [comment]
The files that end up in `/tmp` are all of the naming format that looks something like `.vcf.gz.csi` files, where as the files in `--scratch-dir` are all `.json` files (all with names beginning with `tmp` followed by seemingly random numbers and letters).
